name: Portability Testing

on: 
  push:
    branches:    
      - main
      - master
  pull_request:
    branches:    
      - main
      - master


jobs:
  test_native:
    name: Test Installation in a Native OS Development Environment
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Directory Information
        run: |
          echo '$HOME='"$HOME"
          ls -lAh "$HOME"
          echo "pwd=$(pwd)"
          ls -lAh
          echo '$GITHUB_WORKSPACE='"$GITHUB_WORKSPACE"

      - name: Run Dotfiles Installer Script
        run: ./script/bootstrap

      - name: Test Utilities
        run: |
          if test ! "$(which kubectl)"; then
            echo "--Failure--"
            echo "kubectl not installed"
            return 1
          else
            echo "--Success--"
            echo "kubectl is installed"
          fi


  test_containerized:
    name: Test Installation in a Containerized Development Environment
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: [
          'mcr.microsoft.com/vscode/devcontainers/universal:1-linux',
          'mcr.microsoft.com/vscode/devcontainers/base:focal',
          'mcr.microsoft.com/vscode/devcontainers/base:bullseye'
        ]
    env:
      CODESPACES_CLONE_PATH: /workspaces/.codespaces/.persistedshare/dotfiles
    defaults:
      run:
        working-directory: ${{ env.CODESPACES_CLONE_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: After Checkout - Directory Information
        run: |
          echo '$HOME='"$HOME"
          ls -lAh "$HOME"
          echo "pwd=`pwd`"
          ls -lAh
          echo '$GITHUB_WORKSPACE='"$GITHUB_WORKSPACE"
          ls -lAh "$GITHUB_WORKSPACE"
        working-directory: ${{ github.workspace }}

      - name: Move Repo
        run: |
          mkdir -p /workspaces/.codespaces/.persistedshare/dotfiles
          cp -r "$GITHUB_WORKSPACE"/. /workspaces/.codespaces/.persistedshare/dotfiles
          rm -rf "$GITHUB_WORKSPACE"/*
        working-directory: ${{ github.workspace }}

      - name: Print Context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}

      - name: After Directory-Manipulation - Directory Information
        run: |
          echo '$HOME='"$HOME"
          ls -lAh "$HOME"
          echo "pwd=`pwd`"
          ls -lAh
          echo '$GITHUB_WORKSPACE='"$GITHUB_WORKSPACE"
          ls -lAh "$GITHUB_WORKSPACE"

      - name: Run Dotfiles Installer Script
        run: ./script/bootstrap

      - name: Test Utilities
        run: |
          if test ! "$(which kubectl)"; then
            echo "--Failure--"
            echo "kubectl not installed"
            exit 1
          else
            echo "--Success--"
            echo "kubectl is installed"
          fi
